#!/bin/bash
sudo yum update -y
sudo yum install -y python3-pip
sudo yum install -y python3
export APP_NAME=network_app
export LAB_ID=18d26286-5a1d-4374-94f3-cd09a99e0886
export PROVISION_BUCKET_NAME=pu-base-buckets-v1-provision-lab
EC2_FILES="lab app.py requirements.txt templates/index.html static/jquery-3.5.1.min.js static/images/fullpic.png static/images/loader.gif static/images/right.png static/images/subnett.png static/images/vpc.png static/images/wrong.png"

mkdir /home/ec2-user/$APP_NAME
mkdir /home/ec2-user/$APP_NAME/templates

for file_ in $EC2_FILES
do
  aws s3 cp s3://$PROVISION_BUCKET_NAME/$LAB_ID/$APP_NAME/$file_ /home/ec2-user/$APP_NAME/$file_
done

mv /home/ec2-user/$APP_NAME/lab /etc/rc.d/init.d/
chmod +x /etc/rc.d/init.d/lab
chkconfig lab on

sudo chown -R ec2-user:ec2-user /home/ec2-user/$APP_NAME
sudo pip3 install -r /home/ec2-user/$APP_NAME/requirements.txt

service lab start
