#!/bin/bash
mkdir -p $(dirname '/home/ec2-user/offline_packages.tar')
aws s3 cp 's3://lab-resources-d41cc7f0-14b8/offline_packages.tar' '/home/ec2-user/offline_packages.tar'
mkdir -p $(dirname '/home/ec2-user/sample_app/lab')
aws s3 cp 's3://lab-resources-d41cc7f0-14b8/sample_app/lab' '/home/ec2-user/sample_app/lab'
mkdir -p $(dirname '/home/ec2-user/sample_app/app.py')
aws s3 cp 's3://lab-resources-d41cc7f0-14b8/sample_app/app.py' '/home/ec2-user/sample_app/app.py'
mkdir -p $(dirname '/home/ec2-user/sample_app/requirements.txt')
aws s3 cp 's3://lab-resources-d41cc7f0-14b8/sample_app/requirements.txt' '/home/ec2-user/sample_app/requirements.txt'
mkdir -p $(dirname '/home/ec2-user/sample_app/templates/index.html')
aws s3 cp 's3://lab-resources-d41cc7f0-14b8/sample_app/templates/index.html' '/home/ec2-user/sample_app/templates/index.html'
cd /home/ec2-user
python3 -m ensurepip --default-pip
tar -xzf offline_packages.tar
export APP_NAME=sample_app
mv /home/ec2-user/$APP_NAME/lab /etc/rc.d/init.d/ &&
chmod +x /etc/rc.d/init.d/lab &&
chkconfig lab on &&
sudo chown -R ec2-user:ec2-user /home/ec2-user/$APP_NAME &&
pip3 install --no-index --find-links=/home/ec2-user/offline_packages/ -r /home/ec2-user/$APP_NAME/requirements.txt &&
service lab start
